### ISSUE TITLE
Design The Architecture And Development Plan Of The Host FN Framework

### ISSUE THREAD

**Issue by autholykos** [dusk-network/rusk-vm#145]

**Comment by krl** [comment]
Architectural desicion:

We should aim to re-use the current query/transaction used for inter-contract calls to define and call host functions.

Instead of a `ContractId` we have a `HostModuleId` or similar, that gets intercepted by the host and passed on to the user-defined functions.

Host functions will also be organized in modules, like a contract, with different methods attached.

The Rusk-vm instance will in addition to holding the contract state-trie, also maintain a map of host-function modules, that can be called as if they were contracts.
