### ISSUE TITLE
Enable to read the Global State's root hash

### ISSUE THREAD

**Issue by ZER0** [dusk-network/rusk-vm#265]
**Describe what you want implemented** 
The VM should be able to access to the hash of the root of the Global State

**Describe "Why" this is needed**
This is needed for rollbacks and kept in sync with the node.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ureeves** [comment]
After a talk wit @krl he told me that currently one can compute the hash of a structure by using `Canonical`'s `Store::hash()`.
This is not exactly ideal for performace since it seems to be hashing the entire structure every time. Ideally this would be retrievable from the `Hamt` itself.

Could this be done @krl?
