### ISSUE TITLE
VM2 Out of Gas processing

### ISSUE THREAD

**Issue by miloszm** [dusk-network/rusk-vm#342]
**Describe what you want implemented** 
Currently, VM2 does not behave properly in Out of Gas situation. Wasmer out of gas error should be thrown and gas meter should be returned empty.

**Describe "Why" this is needed**
After migration to VM2 this functionality is still missing - Out of Gas scenario should be as graceful and controlled to the user as possible

**Describe alternatives you've considered**
We could catch wasmer trap, but that is less elegant and gas meter state is not predictable.

**Additional context**
There are two tests which make it easy to introduce this feature:
- `fn out_of_gas_aborts_transaction_execution`
- `fn out_of_gas_aborts_query_execution`

**Comment by ureeves** [comment]
Noticing that everything works correctly on the current `master_vm2` branch - as in without the extra calls required to manage scratch growth - I did a test. Starting from the working `master_vm2` I added a "bogus" function to the contract boilerplate:
```
#[no_mangle]
fn #bogus_fn_name(num: i32) -> i32 {
    num * num
}
```

This function then gets called before any transaction in `CallContext::transact` which then causes the `out_of_gas_aborts_transaction_execution` test to fail due to `Trap(UnreachableCode)` - the same failure mode as in `vm2-persistence-compact2`.
This implies the failure is not due to the scratch growth mechanism, and seems to point to a problem with `wasmer` itself. We could see if upgrading the version from `2.0` to `2.2` fixes the issue.

**Comment by ureeves** [comment]
I did another test, this time starting from https://github.com/dusk-network/rusk-vm/commit/b8caf80412ce925ccba1b5914b0282d09ac70ac7 (VM1), and the problem is also present there.

I used a similar approach and added a new `pre_t` export to the `counter` test contract. This function then gets called *before* the call to `t` if it exists. This ensures the equivalent `out_of_gas_aborts_execution` fails when matching on `OutOfGas`. The error is instead `Trap(UnreachableCode)` - the exact same failure mode as in VM2.

Since VM1 uses `wasmer` `2.2`, this also means that an upgrade to in VM2 will *not* fix this issue, and further hints `wasmer` is the source of the issue.

This test can be seen in the `master_vm1_bogus` branch.
